TenisRecorder2/Controllers/FriendsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TenisRecorder2.Controllers
{
    [Authorize]
    public class FriendsController : Controller
    {
        // GET: Friends
        public ActionResult Index()
        {
            return View();
        }
    }
}

TenisRecorder2/Controllers/MatchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TenisRecorder2.Models;
using Microsoft.AspNet.Identity;
using System.Threading.Tasks;

namespace TenisRecorder2.Controllers
{
    [Authorize]
    public class MatchController : Controller
    {

        private ApplicationDbContext _context;
        public MatchController()
        {
            _context = new ApplicationDbContext();
        }
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }
        // GET: Match
        public ActionResult Index()
        {
            var id = User.Identity.GetUserId();
            var userLoggedIn = _context.Users.Where(k => k.Id == id).FirstOrDefault();
            var loggedUserMatchHistory = _context.Matches.Where(lu => lu.Left.Email == userLoggedIn.Email || lu.Right.Email == userLoggedIn.Email).ToList();
            var model = new HistoryAndMatchModelView
            {
                UserList = _context.Users.Where(d => d.Id != id).ToList(),
                MatchHistory = loggedUserMatchHistory
            };
            return View(model);
        }
        [HttpPost]
        public async Task<ActionResult> submitNewMatch(HistoryAndMatchModelView model)
        {
            if (!ModelState.IsValid || model.SelectedUserId == "" || model.SelectedUserId == "Przeciwnik" || model.SelectedUserId == null || model.NewMatch.ScoreLeft < 0 || model.NewMatch.ScoreRight < 0)
            {
                TempData["noValidData"] = "yes";
                return  RedirectToAction("Index");
            }
            string leftUserData = model.SelectedUserId.Split(' ')[2];
            var id = User.Identity.GetUserId();
            var loggedUser = _context.Users.Where(u => u.Id == id).Cast<ApplicationUser>().FirstOrDefault();
            var leftUser = _context.Users.Where(l => l.Email == leftUserData).Cast<ApplicationUser>().FirstOrDefault();
            var newMatch = new MatchModel()
            {
                Left = loggedUser,
                Right = leftUser,
                ScoreLeft = model.NewMatch.ScoreLeft,
                ScoreRight = model.NewMatch.ScoreRight
            };
            _context.Matches.Add(newMatch);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public ActionResult allmatches()
        {
            return View("allmatches");
        }
    }
}

TenisRecorder2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - TenisRecorder</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/lib")
    @RenderSection("scripts", required: false)
</head>
<body>
    <!-- <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
         <div class="container">
             <div class="navbar-header">
                 <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                     <span class="navbar-toggler-icon"></span>
                     <span class="navbar-toggler-icon"></span>
                     <span class="navbar-toggler-icon"></span>
                 </button>

             </div>
             <div class="navbar-collapse collapse">
                 <ul class="nav navbar-nav">
                     <li class="nav-item active">/*Html.ActionLink("Home", "Index", "Home")*/</li>
                     <li class="nav-item active">/*Html.ActionLink("About", "About", "Home")*/</li>
                     <li class="nav-item active">/*Html.ActionLink("Contact", "Contact", "Home")*/</li>
                 </ul>
             </div>
         </div>
     </nav>-->


    <nav class="navbar navbar-expand-lg navbar-dark bg-primary navbar-fixed-top">
        <img src="~/Views/Shared/pilka.png" alt="pilka tenisowa"style="width:5%;height:5%; margin-right:10px;"> @Html.ActionLink("TenisRecorder", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav mr-auto">
                <!-- <li class="nav-item" style="margin:10px;">
        <a class="nav-link" href="#">Profil <span class="sr-only">(current)</span></a>
    </li>-->
                <li class="nav-item" style="margin:10px;">
                    @Html.ActionLink("Moje mecze", "Index", "Match", new { area = "" }, new { @class = "nav-link" })
                </li>
                <li class="nav-item" style="margin:10px;">
                    @Html.ActionLink("Wszystkie mecze", "allmatches", "Match", new { area = "" }, new { @class = "nav-link" })
                </li>
                <li class="nav-item" style="margin:10px;">
                    @Html.ActionLink("Znajomi", "Index", "Friends", new { area = "" }, new { @class = "nav-link" })
                </li>
                <li class="nav-item" style="margin:10px;">
                    <a class="nav-link" href="#">Turnieje</a>
                </li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - TenisRecorder - Piotr Bajorek</p>
        </footer>
    </div>
    <script src="~/Views/jquery.dataTables.min.js"></script>

</body>
</html>